// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjCQYYb0qozdvNH7gpqfjsuVr1gY8uaEs',
    appId: '1:1017123491907:web:23236aa7e44fc5bc4104f6',
    messagingSenderId: '1017123491907',
    projectId: 'saxnpark-d473c',
    authDomain: 'saxnpark-d473c.firebaseapp.com',
    storageBucket: 'saxnpark-d473c.appspot.com',
    measurementId: 'G-CP69WT62DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeS8Is2ENnfdxT0s3g5Dw9ZuQEq73bV-k',
    appId: '1:1017123491907:android:92ead917dc2cca024104f6',
    messagingSenderId: '1017123491907',
    projectId: 'saxnpark-d473c',
    storageBucket: 'saxnpark-d473c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCD8iyUzGIWF1wBf7pBIbgBcYYbZfJNv0',
    appId: '1:1017123491907:ios:caf31050032112d84104f6',
    messagingSenderId: '1017123491907',
    projectId: 'saxnpark-d473c',
    storageBucket: 'saxnpark-d473c.appspot.com',
    iosBundleId: 'com.example.saxnparkApp',
  );
}
